using CareXP.BasicSamples.Pages;
using Serenity.Navigation;

[assembly: NavigationMenu(7950, "Basic Samples/Grids", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Cancellable Bulk Action", typeof(BasicSamplesController), action: "CancellableBulkAction", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Conditional Formatting", typeof(BasicSamplesController), action: "ConditionalFormatting", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Custom Links In Grid", typeof(BasicSamplesController), action: "CustomLinksInGrid", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Drag & Drop in Tree Grid", typeof(BasicSamplesController), action: "DragDropInTreeGrid", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Enabling Row Selection", typeof(BasicSamplesController), action: "EnablingRowSelection", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Grouping and Sum. In Grid", typeof(BasicSamplesController), action: "GroupingAndSummariesInGrid", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Grid Filtered by Criteria", typeof(BasicSamplesController), action: "GridFilteredByCriteria", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Initial Value for Quick Flt.", typeof(BasicSamplesController), action: "InitialValuesForQuickFilters", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Inline Action Buttons", typeof(BasicSamplesController), action: "InlineActionButtons", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Inline Image In Grid", typeof(BasicSamplesController), action: "InlineImageInGrid", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Product Excel Import", typeof(BasicSamplesController), action: "ProductExcelImport", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Quick Filter Customization", typeof(BasicSamplesController), action: "QuickFilterCustomization", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Removing Add Button", typeof(BasicSamplesController), action: "RemovingAddButton", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Stored Procedure Grid", typeof(BasicSamplesController), action: "StoredProcedureGrid", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Tree Grid", typeof(BasicSamplesController), action: "TreeGrid", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/View Without ID", typeof(BasicSamplesController), action: "ViewWithoutID", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Visual Studio Gallery Q & A", typeof(BasicSamplesController), action: "VSGalleryQA", Permission= CareXP.Administration.PermissionKeys.Devs)]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Wrapped Headers", typeof(BasicSamplesController), action: "WrappedHeaders", Permission= CareXP.Administration.PermissionKeys.Devs)]